# Generated by Django 4.2.4 on 2023-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0002_rename_piechart_costfinder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfinder',
            name='area',
            field=models.IntegerField(max_length=300),
        ),
    ]
