# Generated by Django 4.2.2 on 2023-08-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0003_alter_costfinder_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfinder',
            name='area',
            field=models.PositiveIntegerField(),
        ),
    ]
