# Generated by Django 4.2.2 on 2023-08-08 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0004_alter_costfinder_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfinder',
            name='area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
