# Generated by Django 4.2.2 on 2023-08-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0006_costfinder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfinder',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='default/'),
        ),
    ]
