# Generated by Django 4.2.4 on 2023-08-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0010_alter_costfinder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfinder',
            name='cost_choice',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
