# Generated by Django 4.2.4 on 2023-08-22 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0013_costfinder_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfinder',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.2'),
        ),
        migrations.AddField(
            model_name='costfinder',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
